### ISSUE TITLE
Add a 'reason' when getting disconnected

### ISSUE THREAD

**Issue by Orabig** [plicease/AnyEvent-WebSocket-Client#30]
The "finish" message comes with no information : 

    $this->{WSHANDLE}->on(finish => sub {
			my($cnx) = @_;
			# ...
    }

However other implementations of websockets do provide a "reason" field allowing to know why the connection is down. Is it possible to add it in this module ?

**Comment by plicease** [comment]
I can give you the `$message` that comes from an on_error event from AnyEvent::Handle.  On a clean close (on_eof) this will be `undef`.  See the `on_error` branch I just created.  Is that along the lines of what you were thinking?

**Comment by Orabig** [comment]
Tried, but unfortunately, this does not give the piece of information I'm looking for (in my case, this is an EOF)

Another port (Javascript) of the project I'm working on is having this useful information : https://github.com/centrifugal/centrifuge-js/blob/master/src/centrifuge.js#L546
I don't know where is the missing point in our Perl module. Maybe down to AnyEvent::Handle.on_eof object ?

**Comment by FZambia** [comment]
@plicease The thing @Orabig is talking about is code and reason from Websocket close frame described here  https://tools.ietf.org/html/rfc6455#section-5.5.1

**Comment by plicease** [comment]
Ah.  I think this is doable.

**Comment by plicease** [comment]
Try the branch `connection-code-reason`.  You should be able to get the close code and reason from the connection object either in the finish callback or after.

**Comment by Orabig** [comment]
Yeah, just perfect dude !
Thank you so much, you rock :)
The $cnx->close_reason() actually gives me the correct information.

**Comment by plicease** [comment]
I've released this change as development version 0.40_01 on its way to CPAN now.  If it looks good in cpantesters I expect to do a production release sometime this week.  Please feel free to ping me on this issue if a production release isn't made by Thursday.

**Comment by Orabig** [comment]
Is it thursday ? ;)

**Comment by plicease** [comment]
Thanks for reminding me.  I was going to look at this this morning, but then got distracted by something else.  Unfortunately, there was a bug in the test suite that surfaced in the 0.40_01 release:

http://matrix.cpantesters.org/?dist=AnyEvent-WebSocket-Client+0.40_01

I expect the failures on 5.8.x ( #19 ), but not on the various BSDs and Windows.

I believe this is fixed with this commit:

108553f16f123662670c5895f245a8b0caa51d41

I'd like to do another dev release and see how cpantesters responds.  I am going to now aim for a Monday release if 0.40_02 looks good.

**Comment by Orabig** [comment]
Ok, no prob.

**Comment by plicease** [comment]
The last release is looking really good.  I am going to go ahead and cut a production release early.  0.41 is on its way to CPAN now.
