### ISSUE TITLE
Support for http_proxy

### ISSUE THREAD

**Issue by afresh1** [plicease/AnyEvent-WebSocket-Client#36]
We attempted to use this module, specifically via [Bot::Backbone::Service::SlackChat](https://metacpan.org/pod/Bot::Backbone::Service::SlackChat), but our network requires http traffic to Slack to go through our proxy server.  As we have been unable to find the time to create a patch for this internally we are hoping someone else will be able to.

[AnyEvent::HTTP does have some proxy support](https://metacpan.org/pod/AnyEvent::HTTP#AnyEvent::HTTP::set_proxy-"proxy-url") which may be a useful reference.

[LPW::UserAgent has a lot more code to detect the proxy](https://metacpan.org/source/OALDERS/libwww-perl-6.33/lib/LWP/UserAgent.pm#L1071), which is then used by [LWP::Protocol::http](https://metacpan.org/source/OALDERS/libwww-perl-6.33/lib/LWP/Protocol/http.pm#L144).

**Comment by plicease** [comment]
I welcome a patch for this.  atm I don't have time to do it myself.

**Comment by debug-ito** [comment]
I'm interested in this issue, because our company also has a proxy in front of the public Internet.

It looks like Mojo has better support for proxies (as usual)

- https://metacpan.org/pod/Mojo::UserAgent

I think AnyEvent in general could use a better tool for proxies. I'm gonna think about it..

**Comment by debug-ito** [comment]
I just released [AnyEvent::Connector](https://metacpan.org/release/TOSHIOITO/AnyEvent-Connector-0.01). 

So, by adding `tcp_connect` to AE::WS::Client similar to [AnyEvent::HTTP](https://metacpan.org/pod/AnyEvent::HTTP), we can use AnyEvent::Connector to handle proxy connection, and AE::WS::Client to handle WebSocket session. Or we can add a more straightforward option to AE::WS::Client for proxy config.

@plicease what do you think about it? If you are busy, I'll make a pull-request.

**Comment by plicease** [comment]
I would be thrilled to review a PR👍🏻😀

**Comment by debug-ito** [comment]
OK, I'll give it a try :)

**Comment by plicease** [comment]
@afresh1 I am uploading `0.45_01` with @debug-ito's changes, can you see if that does what you need?

I do not atm have a proxy configured handy to test this, but expect to find some time in the next couple of days before any production release.

**Comment by plicease** [comment]
I want to leave this open for now.

**Comment by plicease** [comment]
After a few days of cpantesters results, it looks good to me, so I am doing a production release as 0.46.  Please let me know if you have any troubles.

**Comment by afresh1** [comment]
I haven't had time to check github this week, but I'll have the folks try this out this week.  Thank you so much @debug-ito !
