### ISSUE TITLE
$self passing out of scope in sub BUILD

### ISSUE THREAD

**Issue by akalinux** [plicease/AnyEvent-WebSocket-Client#40]
I Found this bug in the current version of AnyEvent::WebSocket::Connection.pm on CPAN

When using AnyEvent::WebSocket::Server AnyEvent::WebSocekt::Connection looses scope of $self, this is caused by an un-needed call to Scalar::Util::weaken.  Simply commenting out the call to weaken fixes the issue.

$strong_self in most places should prevent $self's destruction, there is no need to call weaken.

Diff to Connection.pm (bug fixed )

```
86c86
<   Scalar::Util::weaken $self;
---
>   #Scalar::Util::weaken $self;

```

Unit test Below ( may want to conditionally check for AnyEvent::WebSocket::Server) 
##########
```perl
use Modern::Perl;
use Test::More qw(no_plan);
use Data::Dumper;
use AnyEvent::WebSocket::Server;
use AnyEvent::Socket qw(tcp_server);
use AnyEvent::WebSocket::Client;
use AnyEvent;

my $cv=AnyEvent->condvar;
my $port=2049;
my $server = AnyEvent::WebSocket::Server->new();
my $user;
my $listener=tcp_server undef, $port,sub {
    my ($fh)=@_;
    $server->establish($fh)->cb(sub {
      my ($conn)= eval { shift->recv };

      if($@) { 
        close($fh);
        return;
      }
      $conn->on(each_message=>sub {
        my ($c,$msg)=@_;
        my $text=$msg->decoded_body;
        diag $text;
        $conn->send($text);
        $user=$conn;
      });

      $conn->on(finish=>sub {
        diag "server closing connection";
      });
    });
};
my $t=AnyEvent->timer(cb=>sub {
    $cv->send("connection timed out");
  },after=>10);
my $x=AnyEvent->timer(cb=>sub {
  my $url="ws://localhost:$port/test";
  my $client=AnyEvent::WebSocket::Client->new();
  $client->connect($url)->cb(sub {
    my ($conn)=eval { shift->recv };
    if($@) {
      diag "Failed to connect to $url, error was: $@";
      return;
    }
    $conn->send('ok');
    $conn->on(each_message=>sub {
        my ($c,$msg)=@_;
        my $text=$msg->decoded_body;
        diag $text;
        $cv->send($text);
    });
    $conn->on(finish=>sub {
      diag "client closing connection";
    });
  });


},after=>0);
cmp_ok($cv->recv,'eq','ok');
done_testing;
```

**Comment by debug-ito** [comment]
As an author of `AnyEvent::WebSocket::Server`, I comment on this:

I think `weaken` in `BUILD` is necessary because there is a cyclic reference like:

    $self --> handle(AnyEvent::Handle) --> on_error/on_eof --> $finish(closure) --> $self

As for the error in your unit test, you have to take care of Client's $conn not being destroyed. To do that, create a cyclic reference deliberately.

```perl
$conn->on(finish=>sub {
  diag "client closing connection";
  undef $conn;  ## add this line.
});
```

With this modification, the test passes.

**Comment by akalinux** [comment]
Huh.. this does fix it..

**Comment by plicease** [comment]
I agree with @debug-ito I believe the weaken is correct.

**Comment by akalinux** [comment]
ya pod also says to do this.. ok closing the bug.
