### ISSUE TITLE
create non mojo version of t/mojo_close.t

### ISSUE THREAD

**Issue by plicease** [plicease/AnyEvent-WebSocket-Client#7]

**Comment by jjatria** [comment]
Oh, I just noticed this. I used `mojo_close.t` as the base for the tests of my recent pull request (#23). Should those tests be re-worked as well?

**Comment by jjatria** [comment]
I could help with this. If it's alright with you, I'll give it a shot and report back when I have something to show. 

Any pointers welcome!

**Comment by plicease** [comment]
@jjatria just some background, the idea originally in using Mojolicious to test was that there was an existing pretty good implementation of websockets to test against/with.  Unfortunately the mojo project had the habit of frequently making breaking changes, so I wanted to have something more stable to test against.  I still think this would be a good idea, but on the other hand the mojo project seems to have stabilized somewhat as well, so it definitely does not seem as urgent as it once did.  If you take a look you will see there are pairs with equivalent testing going on, for example: ae.t / mojo.t and ae_ssl.t / mojo_ssl.t .  Ideally we'd have ae*.t equivalents to all of the mojo*.t tests.

So if you have time and the interest, I am always glad to see improvements submitted to my dists!
